// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CreateTask: typeof import('./src/components/CreateTask.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    NTimePicker: typeof import('naive-ui')['NTimePicker']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
  }
}
